name: regression


on:
  push:
    branches:
      - 'develop'
    pull-request:
      branches:
      - 'develop'

jobs:
  hello:
    runs-on:ubuntu-latest

  steps:
    - name: Hello Step
      run: echo "Hello world"