name: Regression

on:
  push:
    branches:
      - 'main'
    pull-request:
      branches:
      - 'main'

jobs:
  Regression:
   runs-on: ubuntu-latest

   steps:
    - name: Regression
      uses: actions/checkout@v3
    - name: SetUp Maven
      uses: actions/setup-mvn@v2
      with:
        mvn-version: 3.9.4
    - name: Install Dependencies
      run: mvn clean
    - name: Run test
      run: mvn test -Dtestng=regression

