name: Regression


on:
  push:
    branches:
      - 'main'
    pull-request:
      branches:
      - 'main'

jobs:
  Regression:
   runs-on: ubuntu-latest

   steps:
    - name: Regression
      run: mvn -f path/to/pom.xml test-Dtestng=regression