name: Regression

on:
  push:
    branches:
      - 'main'
    pull-request:
      branches:
      - 'main'

jobs:
  Regression:
   runs-on: ubuntu-latest

   steps:
     - uses: actions/checkout@v3
     - uses: actions/setup-java@v3
       with:
         java-version:  '11'
     - name: Install Maven
       run: |
         curl -fsSL https://get.maven.org/download/apache-maven-3.9.4-bin.zip -o apache-maven-3.9.4-bin.zip
         unzip apache-maven-3.9.4-bin.zip
         export PATH=$PATH:/home/runner/.mvn/apache-maven-3.9.4/bin
     - name: Run Tests
       run: mvn test -Dtestng=regression

